elasticsearch:
   image: elasticsearch:2.4
   ports:
   - "9200:9200"
redis:
  image: redis
  ports:
  - "127.0.0.1:6379:6379"
ldap:
  image: greggigon/apacheds
  volumes:
  - ./ldap-bootstrap:/bootstrap
  ports:
  - "127.0.0.1:10389:10389"
  environment:
  - BOOTSTRAP_FILE=/bootstrap/demo.ldif
  restart: always
oauth:
  image: plone/plone.oauth
  ports:
  - "6543:6543"
  